### ISSUE TITLE
Support extrapulation of the fitting function

### ISSUE THREAD

**Issue by saroad2** [EddLabs/eddington-gui#15]
Description
=======

One should be able to define the domain of the `x` values in which to extrapolate the fitting function to see how it behaves outside the data domain.

Implementation Suggestion
==================

We should add a *min x* and *max x* text input in the main box, which allows the user to define for which `x` values to plot the fitting function results. In that way, we could see how the fitting function behaves outside the fitting data domain.

**Comment by OhadNir9** [comment]
I'm on it

**Comment by saroad2** [comment]
Fixed in #34
