### ISSUE TITLE
Add "Save" button to FigureWindow

### ISSUE THREAD

**Issue by saroad2** [EddLabs/eddington-gui#18]
When displaying a FigureWindow, it should have a "save" button that opens a directory dialog.
the user should choose  directory and the figure should be saved to a file in this directory.

**Comment by OhadNir9** [comment]
I didn't manage to add a button below the chart in the FigureWindow class.
I tried to add the button as a second children of the self.content box, but it seems that nothing changed in the figure window.
The toga-chart module lacks in documentation and examples, if you can provide example of box with elements besides the chart, I'll try to solve the issue.

**Comment by saroad2** [comment]
Hi Ohad,

I believe the reason you're experiencing this problem is that the size of the `FigureWindow` component is set to be the exact size of the *matplotlib* figure object. If you'll remove this restrictions, I believe you'll see the button too.
 
If you keep having this issue, please let me know. It could be a bug in BeeWare.

**Comment by OhadNir9** [comment]
Thanks, locating the button next to the chart and not below it solved the issue.
On another matter, I think that there's another <a href="https://github.com/beeware/toga/issues/1034">bug</a> in Beeware realted to this feature.

**Comment by saroad2** [comment]
Ye, saw your PR on Toga!
It's great to so your dedication and your contribution both here at Eddington and at BeeWare. Thank you!
