### ISSUE TITLE
[Feature Proposal] *Add option for changing the y label of the residuals graph*

### ISSUE THREAD

**Issue by sonicrs** [EddLabs/eddington-gui#70]
Currently, it is not possible to have the y label on the residuals graph be different than that of the main graph, _i.e_ have a graph with labels x,y and a residual graph with labels x,z, or with labels x,y-f(x). In some cases this feature would be useful, as the residuals graph's y axis may be essentially different from that of the regular fit result graph.

**Comment by saroad2** [comment]
Solved in #73
