### ISSUE TITLE
[Bug] fits/graphs wont save to desired folder

### ISSUE THREAD

**Issue by idofanto** [EddLabs/eddington-gui#82]
**Describe the bug**
when wanting to save a ploted fit after saving the fit to the desired location the fit/image doesnt show there even though no error message shows/

**Expected behavior**
the fit should show at the desired location after saving.

**Context**
after preforming a fit i wanted to save the graphs to my folder of the experiment but when i went to look for the graph in the folder it wasnt there' i tried again with differnt fits but nothing showd

 - Eddington version:  latest
 - Operating system: Windows 10

**Comment by saroad2** [comment]
Problem should be fixed in a future release. Closing it for now.
